services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gobarber
    ports:
      - 5432:5432
    volumes:
      - "./postgresql:/var/lib/postgresql"

  localstack:
    container_name: localstack
    restart: on-failure
    image: localstack/localstack:stable
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - SERVICES=s3
      - LS_LOG=error
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/aws.sh:/etc/localstack/init/ready.d/aws.sh"

  app:
    container_name: gobarber-api
    restart: on-failure
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3333
      - DATABASE_URL=postgresql://postgres:password@db:5432/gobarber
      - JWT_SECRET=7ca5c808b68c8eda4b06a4df2b98f90f
      - JWT_EXPIRES-IN=1d
      - AWS_ACCESS_KEY=accesskey
      - AWS_SECRET_KEY=secretkey
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_S3_BUCKET_NAME=gobarber
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db
      - localstack
